version: '3'
services:
  frontend:
    image: portfolio-front
    build:
      context: frontend
      dockerfile: Dockerfiles/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ${PWD}/frontend/src:/app/src
  backend:
    image: portfolio-back
    build:
      context: backend
      dockerfile: Dockerfiles/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/backend/src:/usr/src/app/src